New_Map
6 6

  1   1   1   1   1   1 
  1   4   4   4   4   1 
  1   4   4   4   4   1 
  1   4   4   4   4   1 
  1   4   4   4   4   1 
  1   1   1   1   1   1 


  7   0   0   0   0   4 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  6   2   2   2   2   5 

OPEN_BG

Add: nr: 205
x: 98
y: 499
orient: 2
animated: 0
frames: 0
Add: nr: 220
x: 312
y: 198
orient: 0
animated: 0
frames: 0
Add: nr: 213
x: 60
y: 107
orient: 3
animated: 0
frames: 0
Add: nr: 213
x: 60
y: 177
orient: 3
animated: 0
frames: 0
Add: nr: 213
x: 60
y: 251
orient: 3
animated: 0
frames: 0
Add: nr: 213
x: 60
y: 334
orient: 3
animated: 0
frames: 0
CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

CLOSE_LIGHT

OPEN_COLIDER

Add: 
id: -1
x: 300
y: 50
w: 598
h: 99

Add: 
id: -1
x: 548
y: 299
w: 96
h: 398

Add: 
id: -1
x: 300
y: 548
w: 599
h: 98

Add: 
id: -1
x: 49
y: 299
w: 97
h: 399

Add: 
id: -1
x: 422
y: 248
w: 49
h: 44

Add: 
id: -1
x: 361
y: 246
w: 60
h: 91

CLOSE_COLIDER

OPEN_INTERACTION

Add: 
x: 141
y: 470
w: 24
h: 41
type: 1
ID: 0
info_1: 0
info_2: 120
info_3: 100
info_4: 4

Add: 
x: 109
y: 379
w: 43
h: 13
type: 2
ID: 0
info_1: 0
info_2: 3
info_3: 0
info_4: 0

Add: 
x: 114
y: 298
w: 48
h: 23
type: 2
ID: 0
info_1: 0
info_2: 4
info_3: 0
info_4: 0

Add: 
x: 119
y: 226
w: 47
h: 20
type: 2
ID: 0
info_1: 0
info_2: 5
info_3: 0
info_4: 0

Add: 
x: 118
y: 155
w: 41
h: 24
type: 2
ID: 0
info_1: 1
info_2: 6
info_3: 0
info_4: 0

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
CLOSE_NOTPLAYERCREATURE
file_end