New_Map
6 6

  1   1   1   1   1   1 
  1   0   0   0   0   1 
  1   0   0   0   0   1 
  1   0   0   0   0   1 
  1   0   0   0   0   1 
  1   1   1   1   1   1 


  7   0   0   0   0   4 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  6   2   2   2   2   5 

OPEN_BG

Add: nr: 204
x: 242
y: 3
orient: 0
animated: 1
frames: 4
Add: nr: 204
x: 512
y: 233
orient: 1
animated: 1
frames: 4
Add: nr: 204
x: 253
y: 511
orient: 2
animated: 1
frames: 4
Add: nr: 204
x: -11
y: 220
orient: 3
animated: 1
frames: 4
Add: nr: 212
x: 108
y: 381
orient: 0
animated: 0
frames: 0
Add: nr: 202
x: 216
y: 400
orient: 2
animated: 0
frames: 0
Add: nr: 202
x: 364
y: 408
orient: 2
animated: 0
frames: 0
Add: nr: 202
x: 119
y: 87
orient: 0
animated: 0
frames: 0
Add: nr: 202
x: 225
y: 87
orient: 0
animated: 0
frames: 0
Add: nr: 211
x: 449
y: 33
orient: 0
animated: 0
frames: 0
CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

CLOSE_LIGHT

OPEN_COLIDER

Add: 
id: -1
x: 299
y: 49
w: 599
h: 98

Add: 
id: -1
x: 300
y: 550
w: 601
h: 99

Add: 
id: -1
x: 549
y: 298
w: 98
h: 401

Add: 
id: -1
x: 50
y: 299
w: 99
h: 404

Add: 
id: -1
x: 170
y: 140
w: 48
h: 81

Add: 
id: -1
x: 270
y: 136
w: 47
h: 83

Add: 
id: -1
x: 264
y: 455
w: 64
h: 83

Add: 
id: -1
x: 412
y: 456
w: 56
h: 71

CLOSE_COLIDER

OPEN_INTERACTION

Add: 
x: 392
y: 107
w: 95
h: 100
type: 1
ID: 0
info_1: 0
info_2: 210
info_3: 270
info_4: 8

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
Add:
Nume:   Big Boss
x: 330
y: 130
w: 30
h: 30
skinnr: 3
filenr: 6
Add:
Nume:   Treasire Chest
x: 115
y: 371
w: 100
h: 100
skinnr: 4
filenr: 5
CLOSE_NOTPLAYERCREATURE
file_end