New_Map
10 8

  4   4   4   4   4   4   4   4   4   4 
  4   4   4   4   4   4   4   4   4   4 
  4   4   4   4   4   4   4   4   4   4 
  4   4   4   4   4   4   4   4   4   4 
  4   4   4   4   4   4   4   4   4   4 
  4   4   4   4   4   4   4   4   4   4 
  4   4   4   4   4   4   4   4   4   4 
  4   4   4   4   4   4   4   4   4   4 


  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 

OPEN_BG

Add: nr: 201
x: 368
y: 164
orient: 0
animated: 0
frames: 0
CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

CLOSE_LIGHT

OPEN_COLIDER

Add: 
id: -1
x: 416
y: 228
w: 65
h: 50

CLOSE_COLIDER

OPEN_INTERACTION

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
Add:
Nume:  enemy i
x: 370
y: -30
w: 100
h: 100
skinnr: 3
filenr: 2
Add:
Nume:  enemy ii
x: 876
y: 286
w: 100
h: 100
skinnr: 3
filenr: 2
CLOSE_NOTPLAYERCREATURE
file_end