New_Map
6 7

  1   1   1   1   1   1 
  1   4   4   4   4   1 
  1   4   4   4   4   1 
  1   4   4   4   4   1 
  1   4   4   4   4   1 
  1   4   4   4   4   1 
  1   1   1   1   1   1 


  7   0   0   0   0   4 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  6   2   2   2   2   5 

OPEN_BG

Add: nr: 205
x: 500
y: 186
orient: 1
animated: 0
frames: 0
Add: nr: 205
x: 100
y: 1
orient: 0
animated: 0
frames: 0
Add: nr: 205
x: 1
y: 204
orient: 3
animated: 0
frames: 0
Add: nr: 203
x: 121
y: 337
orient: 0
animated: 0
frames: 0
Add: nr: 205
x: 203
y: 600
orient: 2
animated: 0
frames: 0
Add: nr: 202
x: 330
y: 128
orient: 1
animated: 0
frames: 0
CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

CLOSE_LIGHT

OPEN_COLIDER

Add: 
id: -1
x: 301
y: 50
w: 596
h: 97

Add: 
id: -1
x: 50
y: 349
w: 97
h: 499

Add: 
id: -1
x: 550
y: 349
w: 99
h: 502

Add: 
id: -1
x: 301
y: 649
w: 592
h: 98

Add: 
id: -1
x: 171
y: 388
w: 102
h: 45

Add: 
id: -1
x: 379
y: 179
w: 91
h: 52

CLOSE_COLIDER

OPEN_INTERACTION

Add: 
x: 379
y: 194
w: 26
h: 32
type: 2
ID: 0
info_1: 1
info_2: 5
info_3: 0
info_4: 0

Add: 
x: 466
y: 225
w: 49
h: 28
type: 1
ID: 0
info_1: 1
info_2: 0
info_3: 0
info_4: 0

Add: 
x: 133
y: 97
w: 35
h: 32
type: 1
ID: 0
info_1: 0
info_2: 100
info_3: 400
info_4: 5

Add: 
x: 93
y: 236
w: 44
h: 30
type: 1
ID: 0
info_1: 0
info_2: 450
info_3: 220
info_4: 7

Add: 
x: 240
y: 575
w: 30
h: 34
type: 1
ID: 0
info_1: 0
info_2: 110
info_3: 100
info_4: 6

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
Add:
Nume: workbench
x: 334
y: 154
w: 100
h: 100
skinnr: 4
filenr: 4
Add:
Nume:       Alchemist
x: 171
y: 260
w: 100
h: 100
skinnr: 2
filenr: 3
CLOSE_NOTPLAYERCREATURE
file_end