New_Map
5 7

  1   1   2   1   1 
  1   0   2   0   1 
  1   0   2   0   1 
  1   0   2   0   1 
  1   0   2   0   1 
  1   0   2   0   1 
  1   1   2   1   1 


  7   0   0   0   4 
  3   0   0   0   1 
  3   0   0   0   1 
  3   0   0   0   1 
  3   0   0   0   1 
  3   0   0   0   1 
  6   2   0   2   5 

OPEN_BG

Add: nr: 210
x: 172
y: 0
orient: 0
animated: 1
frames: 4
Add: nr: 210
x: 172
y: 100
orient: 0
animated: 1
frames: 4
Add: nr: 210
x: 172
y: 200
orient: 0
animated: 1
frames: 4
Add: nr: 210
x: 172
y: 300
orient: 0
animated: 1
frames: 4
Add: nr: 210
x: 172
y: 400
orient: 0
animated: 1
frames: 4
Add: nr: 210
x: 172
y: 500
orient: 0
animated: 1
frames: 4
Add: nr: 210
x: 171
y: 600
orient: 0
animated: 1
frames: 4
Add: nr: 205
x: 400
y: 198
orient: 1
animated: 0
frames: 0
Add: nr: 205
x: 1
y: 148
orient: 3
animated: 0
frames: 0
Add: nr: 216
x: 200
y: 210
orient: 0
animated: 1
frames: 1
CLOSE_BG

OPEN_FG

Add: nr: 205
x: 93
y: 598
orient: 2
animated: 0
frames: 0

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

CLOSE_LIGHT

OPEN_COLIDER

Add: 
id: -1
x: 248
y: 318
w: 105
h: 1

Add: 
id: -1
x: 251
y: 219
w: 97
h: 4

Add: 
id: -1
x: 299
y: 456
w: 6
h: 281

Add: 
id: -1
x: 199
y: 460
w: 5
h: 284

Add: 
id: -1
x: 200
y: 160
w: 6
h: 122

Add: 
id: -1
x: 302
y: 157
w: 4
h: 122

Add: 
id: -1
x: 251
y: 48
w: 501
h: 101

Add: 
id: -1
x: 449
y: 348
w: 99
h: 502

Add: 
id: -1
x: 251
y: 650
w: 501
h: 100

Add: 
id: -1
x: 51
y: 349
w: 99
h: 501

CLOSE_COLIDER

OPEN_INTERACTION

Add: 
x: 133
y: 577
w: 28
h: 38
type: 1
ID: 0
info_1: 1
info_2: 0
info_3: 0
info_4: 0

Add: 
x: 94
y: 184
w: 44
h: 20
type: 1
ID: 0
info_1: 0
info_2: 450
info_3: 220
info_4: 4

Add: 
x: 376
y: 238
w: 34
h: 26
type: 1
ID: 0
info_1: 1
info_2: 0
info_3: 0
info_4: 0

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
Add:
Nume:       sewer goblin
x: 140
y: 195
w: 100
h: 100
skinnr: 3
filenr: 2
CLOSE_NOTPLAYERCREATURE
file_end