New_Map
6 4

  1   1   1   1   1   1 
  1   0   0   0   0   1 
  1   0   0   0   0   1 
  1   1   1   1   1   1 


  7   0   0   0   0   4 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  6   2   2   2   2   5 

OPEN_BG

Add: nr: 205
x: 499
y: 145
orient: 1
animated: 0
frames: 0
Add: nr: 205
x: 1
y: 146
orient: 3
animated: 0
frames: 0
CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

CLOSE_LIGHT

OPEN_COLIDER

Add: 
id: -1
x: 301
y: 49
w: 598
h: 98

Add: 
id: -1
x: 299
y: 349
w: 599
h: 98

Add: 
id: -1
x: 547
y: 199
w: 96
h: 202

Add: 
id: -1
x: 50
y: 199
w: 97
h: 200

CLOSE_COLIDER

OPEN_INTERACTION

Add: 
x: 470
y: 190
w: 46
h: 26
type: 1
ID: 0
info_1: 1
info_2: 0
info_3: 0
info_4: 0

Add: 
x: 86
y: 188
w: 41
h: 24
type: 1
ID: 0
info_1: 0
info_2: 440
info_3: 400
info_4: 2

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
CLOSE_NOTPLAYERCREATURE
file_end