New_Map
6 5

  1   1   1   1   1   1 
  1   0   0   0   0   1 
  1   0   0   0   0   1 
  1   5   0   0   0   1 
  1   1   1   1   1   1 


  7   0   0   0   0   4 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  6   2   2   2   2   5 

OPEN_BG

Add: nr: 215
x: 498
y: 298
orient: 1
animated: 0
frames: 0
Add: nr: 205
x: 189
y: 2
orient: 0
animated: 0
frames: 0
Add: nr: 211
x: 105
y: 297
orient: 0
animated: 0
frames: 0
CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

CLOSE_LIGHT

OPEN_COLIDER

Add: 
id: -1
x: 146
y: 354
w: 92
h: 94

Add: 
id: -1
x: 300
y: 50
w: 597
h: 98

Add: 
id: -1
x: 300
y: 450
w: 597
h: 100

Add: 
id: -1
x: 549
y: 249
w: 101
h: 300

Add: 
id: -1
x: 50
y: 248
w: 97
h: 303

CLOSE_COLIDER

OPEN_INTERACTION

Add: 
x: 463
y: 340
w: 51
h: 25
type: 1
ID: 0
info_1: 1
info_2: 0
info_3: 0
info_4: 0

Add: 
x: 100
y: 286
w: 118
h: 115
type: 1
ID: 0
info_1: 0
info_2: 330
info_3: 140
info_4: 9

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
Add:
Nume:  enemy i
x: 301
y: 283
w: 100
h: 100
skinnr: 3
filenr: 2
Add:
Nume:  Enemy ii
x: 163
y: 85
w: 100
h: 100
skinnr: 3
filenr: 2
CLOSE_NOTPLAYERCREATURE
file_end