New_Map
8 7

  1   1   1   1   1   1   1   1 
  1   1   1   1   1   1   1   1 
  1   1   5   5   5   5   5   5 
  1   1   5   5   5   5   5   5 
  1   1   5   5   5   5   5   5 
  1   1   5   5   5   5   5   5 
  1   1   5   5   5   5   5   5 


  7   0   0   0   0   0   0   0 
  3   7   0   0   0   0   0   0 
  3   3   0   0   0   0   0   0 
  3   3   0   0   0   0   0   0 
  3   3   0   0   0   0   0   0 
  3   3   0   0   0   0   0   0 
  3   3   0   0   0   0   0   0 

OPEN_BG

Add: nr: 209
x: 265
y: 1
orient: 0
animated: 1
frames: 4
Add: nr: 209
x: 265
y: 51
orient: 0
animated: 1
frames: 4
Add: nr: 209
x: 265
y: 101
orient: 0
animated: 1
frames: 4
Add: nr: 209
x: 265
y: 151
orient: 0
animated: 1
frames: 4
Add: nr: 210
x: 227
y: 200
orient: 0
animated: 1
frames: 4
Add: nr: 206
x: 184
y: 94
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 421
y: 180
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 393
y: 331
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 269
y: 319
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 223
y: 478
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 606
y: 199
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 526
y: 333
orient: 0
animated: 0
frames: 0
CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

CLOSE_LIGHT

OPEN_COLIDER

CLOSE_COLIDER

OPEN_INTERACTION

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
CLOSE_NOTPLAYERCREATURE
file_end