New_Map
6 6

  1   1   1   1   1   1 
  1   0   0   0   0   1 
  1   0   0   0   0   1 
  1   0   0   0   0   1 
  1   0   0   0   0   1 
  1   1   1   1   1   1 


  7   0   0   0   0   4 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  6   2   2   2   2   5 

OPEN_BG

Add: nr: 205
x: 500
y: 396
orient: 1
animated: 0
frames: 0
Add: nr: 202
x: 85
y: 244
orient: 3
animated: 0
frames: 0
Add: nr: 202
x: 84
y: 311
orient: 3
animated: 0
frames: 0
Add: nr: 202
x: 85
y: 174
orient: 3
animated: 0
frames: 0
Add: nr: 202
x: 293
y: 444
orient: 2
animated: 0
frames: 0
Add: nr: 202
x: 206
y: 447
orient: 2
animated: 0
frames: 0
Add: nr: 205
x: 1
y: 417
orient: 3
animated: 0
frames: 0
Add: nr: 205
x: 270
y: 1
orient: 0
animated: 0
frames: 0
Add: nr: 201
x: 220
y: 49
orient: 0
animated: 0
frames: 0
Add: nr: 201
x: 269
y: 77
orient: 0
animated: 0
frames: 0
Add: nr: 201
x: 314
y: 29
orient: 0
animated: 0
frames: 0
Add: nr: 201
x: 323
y: 94
orient: 0
animated: 0
frames: 0
Add: nr: 204
x: -3
y: 121
orient: 3
animated: 1
frames: 4
Add: nr: 204
x: -2
y: 355
orient: 3
animated: 1
frames: 4
Add: nr: 204
x: 215
y: -3
orient: 0
animated: 1
frames: 4
Add: nr: 204
x: 477
y: 326
orient: 1
animated: 1
frames: 4
CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

Add: 
nr: 1
x: 75
y: 426
range: 81

Add: 
nr: 1
x: 87
y: 179
range: 100

Add: 
nr: 1
x: 270
y: 48
range: 20

Add: 
nr: 1
x: 281
y: 69
range: 88

Add: 
nr: 1
x: 510
y: 378
range: 67

CLOSE_LIGHT

OPEN_COLIDER

Add: 
id: 0
x: 301
y: 49
w: 598
h: 101

Add: 
id: 0
x: 300
y: 549
w: 600
h: 102

Add: 
id: 0
x: 549
y: 298
w: 98
h: 400

Add: 
id: 0
x: 51
y: 297
w: 100
h: 399

Add: 
id: 0
x: 341
y: 148
w: 111
h: 60

Add: 
id: 0
x: 136
y: 291
w: 76
h: 195

Add: 
id: 0
x: 261
y: 123
w: 39
h: 36

Add: 
id: 0
x: 293
y: 474
w: 159
h: 46

CLOSE_COLIDER

OPEN_INTERACTION

Add: 
x: 84
y: 457
w: 38
h: 21
type: 1
ID: 0
info_1: 1
info_2: 0
info_3: 0
info_4: 0

Add: 
x: 157
y: 217
w: 39
h: 16
type: 2
ID: 0
info_1: 1
info_2: 2
info_3: 0
info_4: 0

Add: 
x: 159
y: 286
w: 28
h: 17
type: 2
ID: 0
info_1: 0
info_2: 1
info_3: 0
info_4: 0

Add: 
x: 159
y: 356
w: 26
h: 15
type: 2
ID: 0
info_1: 0
info_2: 1
info_3: 0
info_4: 0

Add: 
x: 482
y: 441
w: 34
h: 18
type: 1
ID: 0
info_1: 1
info_2: 0
info_3: 0
info_4: 0

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
CLOSE_NOTPLAYERCREATURE
file_end