New_Map
8 9

  3   3   0   3   3   3   3   3 
  0   0   0   0   0   0   0   0 
  3   3   3   0   0   3   3   3 
  2   2   3   0   0   3   2   2 
  3   3   3   0   0   3   3   3 
  0   0   0   0   0   0   0   0 
  1   1   1   0   0   1   1   1 
  2   2   2   0   0   2   2   2 
  2   2   2   0   0   2   2   2 


  0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0 
  2   2   6   0   0   5   2   2 
  0   0   3   0   0   1   0   0 
  0   0   7   0   0   4   0   0 
  1   1   1   0   0   1   1   1 
  0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0 

OPEN_BG

Add: nr: 205
x: 200
y: 307
orient: 3
animated: 0
frames: 0
Add: nr: 205
x: 500
y: 296
orient: 1
animated: 0
frames: 0
Add: nr: 205
x: 94
y: 2
orient: 0
animated: 0
frames: 0
Add: nr: 205
x: 391
y: 3
orient: 0
animated: 0
frames: 0
CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

Add: 
nr: 1
x: 534
y: 246
range: 130

Add: 
nr: 1
x: 279
y: 214
range: 189

Add: 
nr: 1
x: 509
y: 432
range: 136

CLOSE_LIGHT

OPEN_COLIDER

CLOSE_COLIDER

OPEN_INTERACTION

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
CLOSE_NOTPLAYERCREATURE
file_end