New_Map
6 5

  3   3   3   3   3   3 
  3   4   4   4   4   3 
  3   4   4   4   4   3 
  3   4   4   4   4   3 
  3   3   3   3   3   3 


  7   0   0   0   0   4 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  3   0   0   0   0   1 
  6   2   2   2   2   5 

OPEN_BG

Add: nr: 205
x: 292
y: 1
orient: 0
animated: 0
frames: 0
Add: nr: 205
x: 0
y: 297
orient: 3
animated: 0
frames: 0


CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

CLOSE_LIGHT

OPEN_COLIDER

Add: 
id: 1
x: 208
y: 137
w: 15
h: 64

Add: 
id: -1
x: 149
y: 201
w: 96
h: 59

Add: 
id: 0
x: 48
y: 248
w: 97
h: 304

Add: 
id: 0
x: 301
y: 450
w: 602
h: 98

Add: 
id: 0
x: 549
y: 249
w: 101
h: 300

Add: 
id: 0
x: 300
y: 49
w: 599
h: 99

CLOSE_COLIDER

OPEN_INTERACTION

Add: 
x: 80
y: 332
w: 36
h: 21
type: 1
ID: 0
info_1: 1
info_2: 420
info_3: 160
info_4: 1

Add: 
x: 337
y: 81
w: 20
h: 43
type: 1
ID: 1
info_1: 1
info_2: 0
info_3: 0
info_4: 0

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
CLOSE_NOTPLAYERCREATURE
file_end
