New_Map
10 7

  2   2   2   2   2   2   2   2   2   2 
  2   2   2   2   2   2   2   2   2   2 
  2   2   2   2   2   2   2   2   2   2 
  2   2   2   2   2   2   2   2   2   2 
  2   2   2   2   2   2   2   2   2   2 
  2   2   2   2   2   2   2   2   2   2 
  2   2   2   2   2   2   2   2   2   2 


  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0 

OPEN_BG

Add: nr: 206
x: 353
y: 78
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 605
y: -15
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 720
y: 35
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 838
y: 2
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 512
y: 58
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 423
y: -7
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 267
y: -3
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 206
y: 99
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 130
y: 6
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 92
y: 293
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 341
y: 319
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 149
y: 350
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 231
y: 316
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 456
y: 367
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 557
y: 284
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 645
y: 360
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 863
y: 339
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 746
y: 295
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 88
y: 104
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 25
y: 331
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: -4
y: 372
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: 32
y: -6
orient: 0
animated: 0
frames: 0
Add: nr: 206
x: -29
y: 62
orient: 0
animated: 0
frames: 0
CLOSE_BG

OPEN_FG

CLOSE_FG

OPEN_DYNAMIC

CLOSE_DYNAMIC

OPEN_LIGHT

CLOSE_LIGHT

OPEN_COLIDER

CLOSE_COLIDER

OPEN_INTERACTION

CLOSE_INTERACTION

OPEN_NOTPLAYERCREATURE
CLOSE_NOTPLAYERCREATURE
file_end